# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.srcs/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/design_1_HBIRD_E203_0_0.xci
# IP: The module: 'design_1_HBIRD_E203_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] -quiet

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm_ooc.xdc

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/arty-master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HBIRD_E203_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.srcs/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/design_1_HBIRD_E203_0_0.xci
# IP: The module: 'design_1_HBIRD_E203_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] -quiet

# IP: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/reset_sys/reset_sys.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==reset_sys || ORIG_REF_NAME==reset_sys} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mmcm || ORIG_REF_NAME==mmcm} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/mmcm/mmcm_ooc.xdc

# XDC: /home/michelle/Desktop/Xilinx/vivado/Hbird_axi/Hbird_axi.gen/sources_1/bd/design_1/ip/design_1_HBIRD_E203_0_0/src/arty-master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_HBIRD_E203_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
